--Listing 7-8.  First Scenario DTA Utility Syntax
dta
-S STR8-SQL-12\SQL2012 -E
-D AdventureWorks2012
-d AdventureWorks2012
-ip
-s 'First Scenario'
-Tl AdventureWorks2012.dbo.SalesOrderDetail
-of 'C:\Temp\First Scenario.sql'
-fa NCL_IDX
-fp NONE
-fk ALL